// Theme A "Clean Pro" — copied from design/desktop-qa/uploads/QA-Tools (1)/qa-tokens.jsx.
// Only the tokens the shell actually uses. Copy more from qa-tokens.jsx as screens land.
// Theme B "Dev Dark" has no mockup (design/README.md) — one theme until it does.
export const t = {
  bg: '#F5F7FA',
  surface: '#FFFFFF',
  rail: '#1A2233',
  railBorder: '#243044',
  railText: '#7A8BA8',
  railActive: 'rgba(59,130,246,0.14)',
  railActiveText: '#93C5FD',
  railActiveBorder: '#3B82F6',
  border: '#DDE3EB',
  text: '#111827',
  text2: '#6B7280',
  text3: '#9CA3AF',
  surface2: '#EEF2F7',
  borderSubtle: '#EEF2F7',
  accent: '#2563EB',
  accentLight: '#EFF6FF',
  accentBorder: '#BFDBFE',
  pass: '#16A34A',
  passLight: '#F0FDF4',
  passBorder: '#BBF7D0',
  fail: '#DC2626',
  failLight: '#FEF2F2',
  failBorder: '#FECACA',
  warn: '#B45309',
  warnLight: '#FFFBEB',
  warnBorder: '#FDE68A',
  blocked: '#7C3AED',
  blockedLight: '#F5F3FF',
  blockedBorder: '#DDD6FE',
  skip: '#6B7280',
  skipLight: '#F9FAFB',
  skipBorder: '#E5E7EB',
  font: '"IBM Plex Sans", system-ui, -apple-system, sans-serif',
  mono: '"IBM Plex Mono", "SF Mono", "Menlo", monospace',
  r: '6px',
  rSm: '4px',
  rFull: '999px',
} as const;
